export { default as LoginForm } from '@pages/Auth/Login'
export { default as RegisterForm } from '@pages/Auth/Register'
export { default as HomePage } from '@pages/Home'
export { default as ProductPage } from '@pages/Products'
export { default as CategoriesPage } from '@pages/Categories'
export { default as DetailPage } from '@pages/Detail'
